export const PERMISSIONS={
    ADD_HOTEL : "add_hotel" ,
    EDIT_HOTEL :"edit_hotel",
    DELETE_HOTEL :"delete_hotel",
    VIEW_HOTEL :"view_hotel",
    ADD_ROOM: "add_room",
    EDIT_ROOM: "edit_room",
    DELETE_ROOM: "delete_room",
    VIEW_ROOM: "view_room",
    VIEW_BOOKiNG: "view_booking",
    ADD_BOOKiNG: "add_booking",
    CHANGE_BOOKiNG_STATUS: "change_booking_status",
    CANCEL_BOOKING: "cancel_booking",
    VIEW_MY_BOOKING: "view_my_booking",
    VIEW_DASHBOARD:"view_dashboard",
    VIEW_AMENITIES:"view_amenities",
    EDIT_AMENITIES:"edit_amenities",
    VIEW_IMAGE_GALLERY:"view_image_gallery",
    EDIT_IMAGE_GALLERY:"edit_image_gallery",
    ADD_CITY:"add_city",
    EDIT_CITY:"edit_city",
    DELETE_CITY:"delete_city",
    VIEW_CITY:"view_city",
    VIEW_PROPERTY_TYPE:"view_property_type",
}as const;
